In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [14]:
df = pd.read_pickle('Train2.pkl')

In [15]:
df.head()

,total_households,total_individuals,target,dw_00,dw_01,dw_02,dw_03,dw_04,dw_05,dw_06,...,pw_06,ADM4_PCODE,lat,lon,NL,water_community,not_black,not_white,Euro_lang,person_per_household
ward,,,,,,,,,,,,,,,,,,,,,
41601001: Ward 1,1674.45058,5888.20750,16.773757,0.933841,0.000846,0.005490,0.000676,0.000000,0.001372,0.005750,...,0.012928,ZA4161001,-29.682270,24.734743,0.292039,0.043281,0.642545,0.927004,0.845249,3.516501
41601002: Ward 2,1736.99230,6735.33812,21.496661,0.696940,0.001253,0.004402,0.000000,0.002301,0.001323,0.007575,...,0.004131,ZA4161002,-29.119311,24.757737,3.207775,0.113862,0.301572,0.984165,0.888100,3.877587
41601003: Ward 3,2403.57591,7273.04995,10.931425,0.810545,0.004517,0.008891,0.003986,0.007735,0.000956,0.006686,...,0.040881,ZA4161003,-29.142276,25.094093,0.000000,0.193231,0.327548,0.832506,0.581537,3.025929
41601004: Ward 4,1740.78737,5734.49046,23.119257,0.659914,0.000000,0.006129,0.000000,0.000813,0.037245,0.005255,...,0.005011,ZA4161004,-29.372052,24.942867,2.038778,0.008369,0.271986,0.999044,0.750342,3.294194
41601005: Ward 5,1730.51451,6657.23835,13.652252,0.950575,0.000655,0.001473,0.000598,0.006999,0.000818,0.004985,...,0.017629,ZA4161005,-29.409381,25.290165,0.000000,0.034150,0.246509,0.893047,0.436975,3.846971

In [13]:
df.columns

Index(['total_households', 'total_individuals', 'target', 'dw_00', 'dw_01',
       'dw_02', 'dw_03', 'dw_04', 'dw_05', 'dw_06', 'dw_07', 'dw_08', 'dw_09',
       'dw_10', 'dw_11', 'psa_00', 'psa_04', 'stv_00', 'car_00', 'lln_00',
       'lan_00', 'lan_01', 'lan_02', 'lan_03', 'lan_04', 'lan_05', 'lan_06',
       'lan_07', 'lan_08', 'lan_09', 'lan_10', 'lan_11', 'lan_12', 'lan_14',
       'pg_00', 'pg_01', 'pg_02', 'pg_03', 'pg_04', 'lgt_00', 'pw_00', 'pw_01',
       'pw_02', 'pw_03', 'pw_04', 'pw_05', 'pw_06', 'ADM4_PCODE', 'lat', 'lon',
       'NL', 'water_community', 'not_black', 'not_white', 'Euro_lang',
       'person_per_household'],
      dtype='object')

In [19]:
df.rename(columns = {'dw_00': 'house_brick', 'dw_01': 'house_hut',
       'dw_02': 'house_flat', 'dw_03': 'house_cluster', 'dw_04': 'house_town', 'dw_05':'house_semi', 'dw_07':'house_shack_bkyd', 'dw_08':'house_shack', 'dw_09':'house_quarters', 'dw_10':'house_tent',
       'dw_11':'house_other', 'dw_06': 'house_bkyd', 'psa_00':'in_school',
       'stv_00':'stv', 'car_00':'car', 'lln_00':'lln', 'lan_00':'Lang_Afk', 'lan_01':'Lang_Eng', 'lan_02':'Lang_IsiN', 'lan_03':'Lang_IsiX',
       'lan_04':'Lang_IsiZ', 'lan_05':'Lang_Sep', 'lan_06':'Lang_Ses', 'lan_07':'Lang_Set', 'lan_08':'Lang_Sig', 'lan_09':'Lang_Sis', 'lan_10':'Lang_Tsh',
       'lan_11':'Lang_Xit', 'lan_12':'Lang_Other', 'lan_14':'Lang_NA', 'pg_00':'Blk', 'pg_01':'Col', 'pg_02':'Asn', 'pg_03':'Wht', 'pg_04':'Other_Race', 'lgt_00':'lgt','pw_00':'tap_in', 'pw_01':'tap_yd',
       'pw_02':'tap_200', 'pw_03':'tap_200_500', 'pw_04':'tap_500_1000', 'pw_05':'tap_1000_plus', 'pw_06':'tap_no'}, inplace = True)

In [20]:
df.columns

Index(['total_households', 'total_individuals', 'target', 'house_brick',
       'house_hut', 'house_flat', 'house_cluster', 'house_town', 'house_semi',
       'house_bkyd', 'house_shack_bkyd', 'house_shack', 'house_quarters',
       'house_tent', 'house_other', 'in_school', 'stv', 'car', 'lln',
       'Lang_Afk', 'Lang_Eng', 'Lang_IsiN', 'Lang_IsiX', 'Lang_IsiZ',
       'Lang_Sep', 'Lang_Ses', 'Lang_Set', 'Lang_Sig', 'Lang_Sis', 'Lang_Tsh',
       'Lang_Xit', 'Lang_Other', 'Lang_NA', 'Blk', 'Col', 'Asn', 'Wht',
       'Other_Race', 'lgt', 'tap_in', 'tap_yd', 'tap_200', 'tap_200_500',
       'tap_500_1000', 'tap_1000_plus', 'tap_no', 'ADM4_PCODE', 'lat', 'lon',
       'NL', 'water_community', 'not_black', 'not_white', 'Euro_lang',
       'person_per_household'],
      dtype='object')

In [22]:
df.to_pickle('Train3.pkl')